[package]
name = "brute-move"
version = "0.1.1"
edition = "2024"
description = "A package for brute-force chess move validation. No pre-calculated bitboards. Tiny storage footprint."

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
schemars = "0.8.3"
serde = "1.0.103"